# Generated by Django 3.0.2 on 2020-01-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laoliprices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPrices',
            new_name='product_price',
        ),
    ]
